### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [sk66641/AquaGuardians#16]
Dear Project Admin, [AquaGuardians](https://github.com/sk66641/AquaGuardians)

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by sk66641** [comment]
@AKSHITHA-CHILUKA 
Ok, done

**Comment by AKSHITHA-CHILUKA** [comment]
add labels to pull requests also

**Comment by AKSHITHA-CHILUKA** [comment]
to both open and closed issues and pull requests or else contributors points will not be counted from your repo

**Comment by sk66641** [comment]
is it necessary to add labels in open prs, i think points gets added once the prs get merged

**Comment by AKSHITHA-CHILUKA** [comment]
no points will be added only if you add labels ,it just take a few second to add labels so please add them

**Comment by sk66641** [comment]
@AKSHITHA-CHILUKA 
Ok, done! I have a doubt like do we need to add level for the issues which are not of either level 1,2 or 3

**Comment by AKSHITHA-CHILUKA** [comment]
they should be in these 3 levels only , every issue should be marked in any one of the level

**Comment by sk66641** [comment]
@AKSHITHA-CHILUKA 
Ok

**Comment by AKSHITHA-CHILUKA** [comment]
also one more thing hacktoberfest-accepted lable for pull request and only hacktoberfest for issues

**Comment by AKSHITHA-CHILUKA** [comment]
Thanks for following all the guidelines , I hope you will be active through out the program and take proper care in assigning the labels .

Thank You ,
Core Team
GSSoC '24 Extended
