### ISSUE TITLE
Add code of conduct and contributing guideline in Readme

### ISSUE THREAD

**Issue by Rx-Metallica** [sk66641/AquaGuardians#2]

**Comment by Rx-Metallica** [comment]
> 

I would like to work on this

**Comment by trishap-16** [comment]
Can you assign me this issue.

**Comment by Pavitra-s-Workspace** [comment]
im interested to contribute,please assign me

**Comment by sk66641** [comment]
@trishap-16 
@Pavitra-s-Workspace 
you can raise another valid issue if you think it needs any change since issues are assigned to first those who comes first and so on
