### ISSUE TITLE
 Sound and Voice Volume Sliders Non-Functional in Preferences Menu

### ISSUE THREAD

**Issue by Lonewolf124** [sk66641/AquaGuardians#3]
**Description:**

The "Sound" and "Voice" volume sliders in the preferences menu currently do not control any audio in the game. Only the "Music" volume slider seems to have an effect, adjusting the overall sound for the game.

Upon reviewing the code, I found that the sliders for "Sound" and "Voice" are present, but they don't seem to be connected to any specific audio channels (like sound effects or voice clips). Additionally, the test buttons for these sliders are also not functional because no sample sound or voice is defined.

Additionally, when using the "Mute All" button, the currently playing music restarts instead of simply being muted, which may be unintended behavior.

![Screenshot 2024-10-02 070224](https://github.com/user-attachments/assets/6d1c14db-0e96-4046-b19b-167e288a1fe0)

**Steps to Reproduce :**

- Go to the Preferences menu.
- Try adjusting the "Sound" or "Voice" volume sliders.
- Notice that no sound or voice clips are played, and the sliders do not change any in-game sound behavior.
- Press the "Mute All" button while music is playing, and notice that the music restarts.

**Expected Behavior:**

- The "Sound" volume slider should control in-game sound effects .
- The "Voice" volume slider should control any voice clips associated with character dialogue or voice-over.
- Test buttons for both sound and voice should play a sample file if available.
- The "Mute All" button should mute the audio without restarting the current track.

**Suggested Solution:**

- Implement sound effects for specific in-game actions, tied to the sound channel, and allow the "Sound" slider to control them.
- Add voice clips for character dialogue or narration, tied to the voice channel, and allow the "Voice" slider to control them.
- Provide sample sound and voice files to test the sliders from the preferences menu.
- Ensure that the "Mute All" button mutes all audio without restarting the currently playing music.
This addition would make the volume controls more functional and improve the user experience.

Note: I am participating in the GirlScript Summer of Code (GSSoC) as a contributor, and I hope to improve the game experience through my suggestions.

**Comment by sk66641** [comment]
@Lonewolf124 
Thanks for your suggestions. So, do you want to contribute?

**Comment by Lonewolf124** [comment]
> @Lonewolf124 Thanks for your suggestions. So, do you want to contribute?

Thank you for asking! Yes, I’d be happy to contribute. I can work on implementing the functionality for the sound and voice sliders as per the issues I raised. If there's any additional guidance you'd like to provide , then feel free to let me know.
