### ISSUE TITLE
UI improvement: enhancing the user experience

### ISSUE THREAD

**Issue by RaginiSharma01** [sk66641/AquaGuardians#6]
# Improvement of user interface
as this application educational game that teaches players the importance of sustainable groundwater management through interactive puzzles, we have to improve the UI of the page 

I want to work on this issue please assign me , to work on it

**Comment by RaginiSharma01** [comment]
Can you please assign me this task

**Comment by jyothimanoj12** [comment]
can you assign this issue to me

**Comment by jyothimanoj12** [comment]
#11 updated for better ui

**Comment by jyothimanoj12** [comment]
done 👍

**Comment by jyothimanoj12** [comment]
hey can you check #10 now and see whether all problems are solved
