### ISSUE TITLE
license and documentation 

### ISSUE THREAD

**Issue by priyanshaggarwal001** [sk66641/AquaGuardians#7]
I would like to add a license file and documentation file of this software listing its feature and uses and some explanation of the code

**Comment by AnujSaha0111** [comment]
Can you assign it to me? I want to work on it.

**Comment by AnujSaha0111** [comment]
Solved in https://github.com/sk66641/AquaGuardians/pull/8

**Comment by Joshjosh27** [comment]
Can you please assign it to me? I can contribute to it

**Comment by sk66641** [comment]
@priyanshaggarwal001 
Could you please give an update over this issue as other contributors are asking for it?

**Comment by priyanshaggarwal001** [comment]
@sk66641  please review the pr request if u want I can change your name in license as I have used @sk66641  and please add the gssoc tags
